services:
  mysql:
    image: mysql:8.0
    container_name: wallet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet_db
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts/init_schema.sql:/docker-entrypoint-initdb.d/init.sql

  wallet-app:
    build: .
    container_name: wallet-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wallet_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./target/wallet-system-1.0.0.jar:/app/app.jar